version: '2'
services:
  
  mongodb:
    image: mongo:latest
    container_name: login-db
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/2C_login_db"
    networks:
      - login-db




volumes:
   mongodata:

networks:
  login-db:
