version: '2'
services:
  login-db:
    image: mysql
    ports:
      - "7004:7004"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: runapp
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: login
      MYSQL_HOST: login-db
  login-ms:
    build: .
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 6004 -b '0.0.0.0'"
    ports:
      - "6004:6004"
    depends_on:
      - login-db
